version: '3.8'

services:
  epub-reader:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
